### ISSUE TITLE
Rank sources

### ISSUE THREAD

**Issue by Ellyster** [neagle/gokibitz#100]
Allow the user to specify in their profile not only their ranks but also where it comes from, since there are huge gaps between KGS, EGF, AGA, Japan, etc ranks.

**Comment by neagle** [comment]
The problem you point out is definitely valid: even KGS / OGS ranks are pretty different. But I'm not sure I want to embrace the complexity of representing different rank sources... I like the simplicity of just claiming one rank, even if it involves a healthy serving of subjectivity.

**Comment by Ellyster** [comment]
Yes, I agree that claiming several can be quite complex, may be worth it, may be not. I also like the simplicity of having a single primary rank.

But, I think that at the very least the user should be allowd to state what is the source of the rank that they claim (<nickname> <rank> on <system>), since it would really help to ajust your expectations to the game and the comments.

**Comment by sphaso** [comment]
I think the complexity arises when you think in terms of behavior. Right now your rank appears along your nickname in the comments. If the have 5+ ranks, what should appear? a mean of those? Should we let the user specify a "primary" rank? (but then, if you think one is your "correct" rank, why list all the others?)

**Comment by neagle** [comment]
Yeah, my concerns are exactly what @sphaso delineated. The problem @Ellyster points out is definitely a real one, and he's a good example as someone whose KGS rank is very different from his rank in Japan, etc. I just can't shake the feeling that it's not worth the extra information and complexity. There's so much simplicity gained in just saying, "What rank do you want to claim? What do you think of yourself as?"

Because, really, there's not too much staked on ranks on GoKibitz except a _general_ idea of how seriously to take your advice. :smile: Which is important! And I do wonder sometimes how we'll handle the inevitable future scenario of someone trying to claim a dan rank who has no business doing so.
