### ISSUE TITLE
Feature: Skip ahead to the next comment or 10 ahead

### ISSUE THREAD

**Issue by mbates314** [neagle/gokibitz#109]
Potential change for the skip 10:
Skip ahead feature will either go to the next comment or to 10 ahead, whichever is fewer. It allows the comments to be viewed without going through all moves.

**Comment by neagle** [comment]
That's an interesting idea. I'm a bit ambivalent about the skip 10 buttons, since I only _ever_ use them accidentally, myself, and have been tempted to dispense with them entirely.

We do have buttons to go to the next / previous comment, as shown here:
![next-comment](https://cloud.githubusercontent.com/assets/176993/10054179/d008f612-61fd-11e5-95c4-be45252b154c.gif)

You can also use `alt + ←` or `alt + →` to navigate between commented moves.

**Comment by mbates314** [comment]
Oh, awesome! Didn't see those buttons there. I'll remember that. Thanks!

I don't use the skip 10 either.
