### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tysonjh** [neagle/gokibitz#110]
It would be great to have the ability to get a blank board.

**Comment by levelonedev** [comment]
Can you give us more details?

**Comment by tysonjh** [comment]
It would be convenient to have a blank board that could be edited, where the user is able to place stones. This could be used for discussing josekis or other sequences.

**Comment by neagle** [comment]
Do you mean like on [Eidogo](http://eidogo.com/)? I agree that it's a good feature. We have the possibility of adding in more board editing capabilities, but right now I don't think I'll be able to prioritize it any time soon, mainly because there are a bunch of other ways to edit a board (relatively) easily and upload it to GoKibitz, and there are still a bunch of high priority items for GoKibitz itself that need addressing. (AHEM, password change?)

I'll keep it in mind for the future! Thanks for taking the time to put in the request. :)
