### ISSUE TITLE
Feature Request - Verified accounts with verified ranking from go servers

### ISSUE THREAD

**Issue by balancego** [neagle/gokibitz#118]
It would be great if there were a way to verify user accounts with go rankings from one of the major internet servers.  Since it is possible to pull KGS data (http://kgs.gosquares.net/) and probably OGS data, it would be good if accounts could verify user's skill level.  This would add more trust to the commenting system.

**Comment by neagle** [comment]
This is something I thought about when creating GoKibitz, as I definitely sympathize with the desire to have the rank commenters claim have some reliability to it. A person's rank is important context to their comments, not that one should ever not carefully listen to a weaker player, but it gives an idea how much strength a player has backing up their arguments.

However, I can't really see how a verified user rank would work in practical terms, since I don't want there to be any requirement that people use a particular server. Also, I'd have to have authenticated integration with that server or else anyone could claim anyone else's rank, and only OGS really offers any robust API.

So, as with many things, I've chosen the simple route. Rank goes by the honor system, and so far it's worked out well.

Thanks for raising the issue!
