### ISSUE TITLE
Private/shared kifus

### ISSUE THREAD

**Issue by rberenguel** [neagle/gokibitz#12]
Well, what the title says. This would be a neat feature for teachers/private study groups, don't you think?

**Comment by neagle** [comment]
I agree. I've thought about at least the private thing before, and deliberately set that aside to focus on what I thought of as the minimum viable product for GoKibitz. Having private kifus that don't show up in public lists shouldn't be too difficult: I already have a `public` flag in the DB. Now that you've mentioned it, I'll bump that up in priority.

**Comment by rberenguel** [comment]
Well, don't work on it if there are more interesting things ;) I just thought this may bump its use-ability by go teachers (a little like the Go Teaching Ladder: post the game and get a notification/ask questions a teacher can answer)

**Comment by neagle** [comment]
There are a million things to work on. But I launched this rather than keep
it private because I needed some encouragement and incentive (I was getting
overwhelmed with all the features it Ought To Have before it was as good as
I wanted it to be), so if someone asks for something and I think it's a
good idea, that helps me know what to prioritize.
