### ISSUE TITLE
Show a "Loading comment" when you know there is a comment

### ISSUE THREAD

**Issue by ajcsimons** [neagle/gokibitz#120]
Someone linked me to your site, and I thought it was broken because the comments don't appear quickly enough if you whiz through the moves with right arrow navigation. From http://www.lifein19x19.com/forum/viewtopic.php?f=15&t=13082:

So the reason I couldn't see comments is because I followed the link, and then held down my right arrow key to whiz through the game and no comments appeared as the stones appeared on the board. That's because the comments are loaded asynchronously by ajax and take a long time to appear, by which time you've moved on to the next move (so you get loads of js errors). I suggest the developer stores a list of the moves with comments on first load (edit: it already has this as on move 0 it lists the moves with comments) so that when you whiz through it knows to display a "Loading comment" message on relevant moves (and not to issue the ajax request for comments immediately on moves the cache suggests have no comments (but have a small chance to have been commented since initial page load)), but wait a short time to reduce the request spam which is presumably why it is a lot slower to load comments after whizzing through moves that if you directly navigate to one with a fresh page request.

**Comment by popz73** [comment]
+1 for this - I found the initial description a bit too focused on a solution proposal, so I'll focus on the issue itself, that seems clear and important to me:

Currently, when browsing through the moves of a game (with the right arrow), **we miss a LOT of the comments** because we're unaware that they exist. The loading takes a while, we don't need to be particularly fast on the browsing to miss them.

The problem is that we don't know that something is loading, there's no indication. If the delay can't be improved, displaying a noticeable "loading comment" would be an acceptable compromise.

I know that some arrows to browse "only moves with comments" exist, but it's not the same thing - seeing the game progression in random jumps is not the same as watching the game unfold move-by-move, and we'd skip through uncommented moves that we would like to comment on.

**Comment by neagle** [comment]
I'll see if I can get the loading indication for you this week. It's a problem I took a crack at a long time ago, and clearly didn't solve adequately. It's also a problem I've let linger largely because I don't have it... maybe my ping is low enough, but I never accidentally miss comments for this particular reason. But missing comments kinda breaks the main point of the site, and it should work better for mobile / people on coffeeshop wifi, etc. Thanks for flagging the importance of this item to you, popz73, I'll see what I can do.

**Comment by neagle** [comment]
Let me know if you have any feedback on the new feature. 😄 

![jan-19-2017 14-05-44](https://cloud.githubusercontent.com/assets/176993/22121116/986a2ab6-de50-11e6-9b4c-a6ba58b12853.gif)

**Comment by popz73** [comment]
Hi! Thanks, but this doesn't help - now what we is have an animation on *every move* for <x>ms until we know the result of the fetch (until we know if there are comments or not).
For slow/far connections (like mine), it actually makes the game browsing experience much busier/distracting.

When browsing through a game, the feedback of the stones is immediate - the info of "comment/no comment" should be too. The idea here (or at least my idea, and my understanding of the opening comment) would be to have this immediate loading indicator *only for moves that contain comments* - for the other ones, nothing will be shown.
This is what will allow us to browse the game and be alerted when actual comments are being loaded, so we don't miss them. If we're alerted *all the time* as we are today, it just becomes a nuisance.

At first load, the "list of moves with comments" should be stored, and those would be the only moves where the loading indicator would be shown. If you want to be perfect and trigger the loading comment for "live" (written after the first load), this list could be refreshed periodically in the background. 
But that part wouldn't be that important, it would be only to cover a very small percentage of cases.

**Comment by neagle** [comment]
Hmmmm, okay, I'm persuaded. I've been reluctant to to additional tracking / storing of comments that aren't the move one is currently on, but after mulling over your description of the problem for a while, I agree with the problem you point out.
