### ISSUE TITLE
Embeds not working

### ISSUE THREAD

**Issue by flakeman2** [neagle/gokibitz#14]
Hey Nate,

Thanks for adding the embed feature to gokibitz.  I'm having problems with the embed feature though.  Are you able to see the source for this preview of a post of mine?

https://php-flakeman2.rhcloud.com/?p=42&preview=true

I believe I've got all the code embedded correctly but let me know if I'm missing something.

Devin

**Comment by neagle** [comment]
Sorry you're having an issue, Devin!

Because I'm not logged in to your WP Admin, I can't see your preview. If you want, you could set me up with an admin account and I can help debug that way. (You can send me details at nate@nateeagle.com)

**Comment by flakeman2** [comment]
Thanks Nate - I just added an admin account for you.  It should have sent you an email with the password.  Let me know if you need anything else.

**Comment by neagle** [comment]
Thanks Devin! That let me figure out the issue pretty quickly.

Your site is served up on `https`, and it won't allow embedding resources from `http` sites. The only real solution is for me to get GoKibitz on `https`, which I'd thought about doing anyway, since that's the direction everyone on the internet is moving in the post-Snowden world. The only thing is that SSL certs cost money, so I'd put off looking into it.

Let me check out my options and get back to you.

**Comment by neagle** [comment]
I've started the process of getting an SSL certificate so I can provide `https`, which is something I've wanted to do anyway. I'll let you know when things are good to go.

**Comment by flakeman2** [comment]
Cool - good to hear :)

**Comment by neagle** [comment]
@flakeman2 Complete! GoKibitz can now be accessed via https, which means it can be embedded on your site. I went ahead and modified your HTML snippet, and it's working in the preview.

Let me know what your experience is with the embedded mode... you'll be the first user to do it.

**Comment by flakeman2** [comment]
Awesome!  Thanks Nate - I'll try and get a post together soon :)
