### ISSUE TITLE
[feature request] let the uploader highlight which color he had in the game

### ISSUE THREAD

**Issue by pgum** [neagle/gokibitz#147]
Just to make easier for the reviewers to see for which player to make a review. I see that many players have the same username across multiple sites, but I have a few on Panda, few on Tygem and other places, and these cannot be not easily connected to my username on gokibitz. So I would suggest that user should be able to select for which colour he would want to get review.  
My English is little clunky today, so I don't know if I phrased it in any way understandable, sorry for that.

**Comment by neagle** [comment]
This is a good idea, actually. It is quite common for the uploader to have to comment "I was black" or whatever at the beginning. Now I just have to think of a way to implement this. 😄

**Comment by pgum** [comment]
For most of the time, I tag my uploads like that :]  
Just idea - maybe two radio buttons on upload page (css'ed like stones), and for viewing bigger text of chosen player or something like that?  
  
Glad I could help :)  
Make that travis green and happy ;]

**Comment by neagle** [comment]
I'm going to close this for now and mark it "somedaymaybe", which is a label I keep around for good ideas that I'm either not sure how to implement right now, or take more time than I have right now.

Right now, I don't think this problem is that acute because the uploader can just comment "I was black", which deals with the problem, albeit inelegantly. But I'll keep it in mind and see if any good implementation ideas occur to me. Thanks for the suggestion, @pgum!
