### ISSUE TITLE
Tiny Style Request

### ISSUE THREAD

**Issue by mooreniemi** [neagle/gokibitz#156]
In this gif, I'm clicking the "next move" button:

![](http://g.recordit.co/FUATsBPbUw.gif)

This jumping up and down of the element while the text element loads is an easy thing to tidy up. I keep thinking someone is maybe starting to chat or adding something.

I may have time soon to do a PR on this, if you're amenable. Like I said, super tiny!

**Comment by neagle** [comment]
A little while ago, I added an animated throbber `.gif` to show during the period where comments were loading, but I ended up finding it more annoying than the problem it solved. I kept the new text "No comments so far" so that there wasn't a period where people might think comments had loaded and there were none when, in fact, they were still loading.

But the jump you point out is annoying and, once you point it out, totally unnecessary.

a) Thank you for the animated `.gif`—there's no clearer way to show a UI issue that involves a transition.

b) Thanks for being so polite in your request!

I've just pushed a commit that places a `<p>&nbsp;</p>` during load that will be the same height as the text that replaces it, which should prevent any more content jumping.

![feb-23-2017 22-49-10](https://cloud.githubusercontent.com/assets/176993/23289814/528404b4-fa1a-11e6-9875-73421695ebce.gif)

Let me know if you have any feedback, and thanks for submitting the issue!

**Comment by mooreniemi** [comment]
No worries! And thanks for your prompt reply. For gifs of this sort, I quite like [recordit](recordit.co). In this case, any reason to not make the load state just default to no comments text? Then at least in the majority of cases I won't see any blip when loading, and if I do, it signals for sure "there's a comment here, go look!" Mostly this is nice for me as I'm flipping through moves looking to see if one actually has a comment.

**Comment by neagle** [comment]
Forgive me if I've misunderstood you: the problem is that when you first go to a move, GoKibitz makes an API call to get comments. During the time it takes that API call to return, it's unknown if there are comments or not.

Up to about a month ago, there was no visual difference between that loading period and the case where no comments were present. That led some users to skip on to the next move, thinking there were no comments, before the API call had returned.

A full solution to this is to load all the comments when you go to any move in a game, or at least to fetch a set of data that shows which moves have comments so that you could show a special loading indicator only when there are actual comments to load. But this requires a fairly significant refactoring of the move/comment code, one that I'm a little reluctant to embark on right now.
