### ISSUE TITLE
Bug: hyperlink markup doesn't work in game comments

### ISSUE THREAD

**Issue by GreenAsJade** [neagle/gokibitz#163]
https://gokibitz.com/kifu/rJLInRslZ

**Comment by neagle** [comment]
Yeah, I decided not to treat game comments as [markdown](https://daringfireball.net/projects/markdown/syntax) since game comments are fundamentally a part of the SGF, and markdown isn't part of the SGF spec. I'd want someone to be able to load SGFs in any editor or site and still have them make sense.

So I do parse them and turn labels and certain keywords (like `move 13`) into interactive elements, but regular markdown won't work.

**Comment by GreenAsJade** [comment]
Yeah, my suggestion is a bit niche use case :)   I just wanted the "introduction" that I wrote to be at "the top" :)
