### ISSUE TITLE
Bug kifu listing page hanging

### ISSUE THREAD

**Issue by buenmate** [neagle/gokibitz#195]
https://gokibitz.com/kifu has been hanging up in Firefox and Chrome on multiple computers for me over the last few days.

**Comment by neagle** [comment]
Sorry to hear you're having trouble! Could you open your browser's console and paste any error messages you see there? The service is still up and running, and I haven't been able to reproduce an error on my end.

**Comment by buenmate** [comment]
I'm not getting anything in the Chrome console. After an initial "Page Unresponsive", it still reads "Waiting for GoKibitz.com...." an hour later while displaying either the background color or everything but the kifu list.

Firefox prompts to wait or close, although I'll have to check the exact message on that system later.

On one of the systems I've tried this on (Windows 10 Pro), the page loads just fine in Edge (which I've only used for this one purpose).

This only started a couple of days ago and is taking place both at home and my office.

If I ctrl-alt-del, kill Chrome, and then restore, it finally displays both the kifu list and comments, but I'm logged out. I reload, and it logs me back in but the problem returns.

So I killed it, went to the main page, logged out, and was then able to view kifu. Once I log back in, the problem resumes.

**Comment by neagle** [comment]
Great debugging, janxter. It sounds like it's something related to your user. I've discovered that I can also turn the page unresponsive with (almost) any search on the public kifu page, regardless of who's logged in. This makes it seem like there's something that now exists in the db related to either a particular user or a particular game that's causing an error.

What's your username?

And is there any chance that you uploaded a particular game or made a change to your profile immediately before this started happening?

**Comment by buenmate** [comment]
I'm user HarveyCrichton and I'm pretty sure the last game I uploaded was https://gokibitz.com/kifu/ByyM3ZeFr

**Comment by neagle** [comment]
Hm—so you had two SGFs uploaded that were truncated at random points.

(Example: "smog山人: if your opponent makes some mistake you can profit from it :). From move 1: D16 Q4 D4 F17 D14 C17 D17 D18 C16 E18 C18 B17 B18 B16 B15 \nsmog山人: if he connects solid you can still play hane if you want. From move 1: D16 Q4 D4 F17 D14 C17 D17 D18 C16 C18 B17 \nsmog山人: if he blocks you there, you're back to the joseki xd. From move 1: D16 Q4 D4 F17 D")

The malformed SGFs were causing a surprisingly complete meltdown of functions that tried to retrieve and parse them. Obviously this shows that the uploader is insufficiently guarded against invalid SGF files: I'll see if I can address that on my side.

Out of curiosity, were you cutting/pasting the text of your SGFs? Is there any chance the truncation was caused by user error?

**Comment by neagle** [comment]
(You should be able to log back in now. I've marked the two invalid SGFs as deleted.)

**Comment by buenmate** [comment]
As it happens, I just linked to the URL instead of downloading from OGS and uploading to GK from my computer for the last few games. Maybe some sketchy network issue took place.

I likely hand-edited text in the game *after* it was in GK, but that seems unlikely to impact the sgf in your db.

**Comment by neagle** [comment]
Hmmm—maybe the hand-editing thing could be a point of vulnerability. Another thing to investigate. If I ever get the chance to do GoKibitz 2.0, I'm going to store SGFs in the DB in a less fragile way.

Thanks for your excellent debugging; sorry again for the inconvenience. Let me know if you have any other issues!
