### ISSUE TITLE
Add a button to go to the next commented move

### ISSUE THREAD

**Issue by git-oca** [neagle/gokibitz#40]
What about adding  buttons to go to the next/previous commented move of a game ?
ideally with a short-cut key like [ctrl]+left/right cursor for example.

**Comment by neagle** [comment]
Sorry I haven't replied to this sooner: this week turned out to be a bit of a vacation from GoKibitz work as I had to really focus on a big project at work and then had a long weekend in West Virginia. This is definitely something we need to have, and I need to figure out the right interface for it. I think your keyboard suggestion is perfect, I just need to figure out the visual side.

**Comment by levelonedev** [comment]
Did you consider how you would visually represent this? My thoughts were to just add a new arrow button with perhaps a talking bubble overlayed on it.

**Comment by neagle** [comment]
Launched last weekend! d79d2410240f1a85f6624321edd743041fa275a1 Thanks again to @git-oca for the suggestion, and to @levelonedev for the implementation.

**Comment by git-oca** [comment]
This is Great !!!
Thank you very much ! I'm not very active as I don't have that much time for 19x19 games right now, but I hope to jump in back soon
Cheers 

Olivier
