### ISSUE TITLE
Deleting a comment produces error and CSS updated incorrectly

### ISSUE THREAD

**Issue by levelonedev** [neagle/gokibitz#43]
![Before Delete](https://cloud.githubusercontent.com/assets/9813893/6262658/ffb68552-b7c4-11e4-8084-6ef427e35150.png)

![After Delete](https://cloud.githubusercontent.com/assets/9813893/6262661/09de8cfa-b7c5-11e4-9684-d9a91b661293.png)

Upon refreshing the page you find that the comment is no longer there.

**Comment by neagle** [comment]
Hm! Is this on live? I just tried deleting comments both as my main account and with a test account and didn't have any problems.

**Comment by levelonedev** [comment]
Yeah! I did more debugging and it appears in chrome under windows as well. 
![chrome_windows_7](https://cloud.githubusercontent.com/assets/9813893/6280874/243074da-b872-11e4-96f0-0386ce504cdf.JPG)

**Comment by neagle** [comment]
Thanks for working this out with me over IM! The problem was that kifu uploaded before [this commit](/neagle/gokibitz/commit/70dfc46cfd6a49657d8b8f7956172c53ba2581bb#diff-261eb9003938fbd86fb86b0c3c06fb20R22), didn't have original games saved. I thought I took care of this by adding a check when kifu were saved or updated, but I forgot that when comments are added to kifu, they have to push a reference to the kifu and save it, too.

Great, great, great job finding this and bringing it to my attention. Thanks!

**Comment by neagle** [comment]
Fixed by 741dbd6298632573cd5cb839ed547f39c4d3c003
