### ISSUE TITLE
Error running npm install involving karma

### ISSUE THREAD

**Issue by tristil** [neagle/gokibitz#51]
I'm trying to figure this out on my own but putting this here to document it. 

From a fresh install when I type `npm install` I get the below error. It mentions karma, which isn't an explicit dependency in `package.json` but is the test runner for Angular. Possibly it's required in `angular-socket-io`? I use karma on other Node projects but I only have it installed locally, not as a global executable.

```
[~/Projects/opensource/gokibitz]$ npm install
npm WARN package.json angular-socket-io@0.7.0 No repository field.
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.1
npm ERR! code EPEERINVALID
 
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.7.3 wants karma@~0.12.0
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.7 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.10 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/method/Projects/opensource/gokibitz/npm-debug.log
```

**Comment by tristil** [comment]
This seems to be an issue with `ng-storage`. See this ticket:  https://github.com/gsklee/ngStorage/issues/77. The suggestion there is to use `ng-locker` instead.

**Comment by neagle** [comment]
@tristil Sorry I wasn't able to get back to you sooner: it's been a rough couple of days as we've been prepping to launch a big update to the CMS I help support.

I'm sorry about the problem you ran into with `ng-storage`... it sucks if the solution is just to replace it entirely, though certainly not the end of the world. I'll check it out tonight and either swap it out or fix it another way.

**Comment by tristil** [comment]
Well what that ticket is saying (more in the comments than the description) is that the project isn't supported anymore and nobody plans to fix the bugs with it. Patching things might be the best solution in the short term but sounds like that package doesn't have a future.

**Comment by tristil** [comment]
Also, I'm curious if you run into the issue on a fresh install of the repo?

**Comment by neagle** [comment]
I looked into this last night, and...

1) "Well what that ticket is saying (more in the comments than the description) is that the project isn't supported anymore and nobody plans to fix the bugs with it. Patching things might be the best solution in the short term but sounds like that package doesn't have a future."

Agreed. And swapping it out with `angular-locker` isn't such a big deal. So for separate reasons, it's worth ditching `ng-storage`.

2) "Also, I'm curious if you run into the issue on a fresh install of the repo?"

Yes: I had to blow away my `node_modules` directory to reproduce the error you were getting, actually. But once I did, I got the error even when trying to install `angular-locker`, and then on other attempts to install things as I was poking around, like `gulp-sass`, for instance. So I think this isn't related directly to `ng-storage`.

I actually think the problem is broader, and closer to what's being reported [here](https://github.com/npm/npm/issues/4749). That said, I haven't managed to fix it yet, on my end. I hope to look at it more later today.

**Comment by neagle** [comment]
Actually, you were right and I was wrong. You're smart and I'm dumb. You're the best, I'm the worst. You're very good-looking, I'm not... uh, attractive.

The problem was _still_ `ng-storage`, despite the crazy way the error was being reported. I had to remove it from my package.json and then remove it from my `node_modules` directory, after which I could install other packages without problem. My eyebrow is still raised over that one. I'll swap in `angular-locker` some time today.
