### ISSUE TITLE
https certificate currently fails for mobile devices 

### ISSUE THREAD

**Issue by levelonedev** [neagle/gokibitz#77]
![screenshot_2015-05-06-16-39-42](https://cloud.githubusercontent.com/assets/9813893/7505322/96df0aa0-f40e-11e4-8eea-ff8e02752b54.png)
Above was tested on Android 
Chrome 42.0.2311.111
Android 5.1.0
Also tested on iPad safari but don't have the version information for that now.

**Comment by neagle** [comment]
Man, it turns out the internet actually [is quite helpful](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/789/37/certificate-installation-nginx) about this issue. This should be resolved now. I tested it on iPhone Safari, which used to give me trouble. Could you double-check on Android? Apparently that's the most demanding of the bunch.

**Comment by levelonedev** [comment]
Works great now!
