### ISSUE TITLE
Import SGFs from other servers (OGS, KGS, etc)

### ISSUE THREAD

**Issue by flakeman2** [neagle/gokibitz#9]
How about being able to pull in sgf files from different online servers?  OGS, KGS, etc. ?

**Comment by neagle** [comment]
I think that's a great idea. The upload page is definitely due for an enhancement: it should at least have most of the features available on Eidog's excellent upload page. (http://eidogo.com/upload) I'll see if I can do one better and make it possible to import files directly from OGS/KGS.

**Comment by horaceho** [comment]
... and IGS please.

**Comment by neagle** [comment]
I've [just added](https://github.com/neagle/gokibitz/commit/65662b88863d8603630e8500d355a0ffa6c6b7ca) the ability to upload files from external URLs with the pattern `https://gokibitz.com/fetch#http://someurl/file.sgf`. That will allow users to log in / sign up if they haven't already, and bring them to a screen where they can select public / private and finish uploading the file.

![image](https://cloud.githubusercontent.com/assets/176993/26113093/94d092ae-3a27-11e7-90ce-ec69d816e5c7.png)

I think rather than going the route of having any kind of UI in GoKibitz that fetches lists of games from other server, the best way is to just allow other servers/clients to add "Open in GoKibitz" if they want.
