### ISSUE TITLE
Comma between moves prevents interaction

### ISSUE THREAD

**Issue by sphaso** [neagle/gokibitz#96]
Hello!
I've just noticed that:
- commenting ("user" comment, not game comment) with a list of comma-separated moves
- when hovering over each coordinate, the latter is not displayed on the board

E.g. https://gokibitz.com/kifu/NJ37JY0N?path=139

I realize this is a bit of a nitpick and I'm not sure how you feel about it. I think it would be nice to have a way to propose a list of alternative moves (so not a sequence) and still have interactivity.

**Comment by neagle** [comment]
Yeah, I've noticed this before, too. The problem is that when I created the sequences feature, it allowed moves to be either space-separated or comma-separated, because I've seen people write sequences that way: "B5, C6, H14", etc. But it's possible we could change that, since the in-game sequence creator seems to have been popular enough that I think every time I see an intended sequence, it's space-separated.

**Comment by levelonedev** [comment]
You could also enclose all sequences in {} to make parsing simpler especially if everyone uses the sequence generator anyway. That way if they type a list of coordinates by hand it would be easier in code to differentiate it.

**Comment by neagle** [comment]
I'm reluctant to use the braces solution, though it has the definite advantage of being totally unambiguous. But I'd like to do my best to work within Markdown's mission of being totally readable text markup outside of any parsing.
